apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::238248347778:role/<EXISTENT_ROLE_INFORMATION>
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::238248347778:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-14T19:52:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1338"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7271e419-2f85-4733-97a0-936773821da0
